Add SQL agent and Spider environment
microsoft/autogen pull request #1218
Opened 2024-01-12 16:01 UTC by byronxu99

## Why are these changes needed?

## Related issue number

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

2024-01-12 16:16 UTC, rickyloynd-microsoft commented
Hi @byronxu99 Can you provide details about this SQL agent and Spider environment, as well as their benefits? The test dir is generally reserved for test scripts to be run by pytest or by users. New agents generally belong under agentchat/contrib.

2024-01-12 18:08 UTC, rickyloynd-microsoft commented
> > Hi @byronxu99 Can you provide details about this SQL agent and Spider environment, as well as their benefits? The test dir is generally reserved for test scripts to be run by pytest or by users. New agents generally belong under agentchat/contrib.
> 
> Hi @rickyloynd-microsoft I moved the agent into the notebook directory as an example, hopefully that's a better place.

Yes, it's simpler. Is this PR just adding a notebook example of how to use SpiderEnv through function calling and SQL? The loop at the bottom of the nb would be convenient if it were inside a .py file, but in the nb it would be better to replace the for loop with a few example turns to illustrate and document the responses that are expected. The other notebooks are organized this way.

Where is spider_env defined? Did that file get dropped from the PR?

At the top of the PR, there should be some explanation of the benefits. ("Why are these changes needed?")

2024-01-12 23:08 UTC, afourney commented
Is the Spider nl2sql benchmark? That would probably fit better under autogenbench

2024-01-25 18:59 UTC, byronxu99 commented
@rickyloynd-microsoft
Hi, we have updated the notebook and PR description. `spider_env` is a Python pip package, and the notebook provides the command for installing it.

@afourney
This PR will just be the demo notebook. Any integration with autogenbench would be for future work.

The PR should now be ready to be merged.

2024-01-25 20:18 UTC, rickyloynd-microsoft approved these changes
Looks good!

2024-01-25 22:19 UTC, afourney approved these changes
LGTM

2024-01-26 17:01 UTC, sonichi commented
Could you add a link in https://microsoft.github.io/autogen/docs/Examples ? That will help with the discoverability.

2024-01-26 18:47 UTC, BeibinLi commented
I am okay with this notebook. However, the agent is designed for "Spider" benchmark, which is not used generally for actual product. For instance, when users want to use a SQL agent, they would not expect to give "reward" or "score" for the answer, as they may not even know the answer.

So, I would suggest to include the name "spider" into the notebook file name.

2024-01-26 21:43 UTC, byronxu99 commented
@sonichi @BeibinLi
The requested changes have been made.

2024-01-26 23:20 UTC, BeibinLi approved these changes
LGTM now~ Thanks!

2024-01-27 17:31 UTC, sonichi requested changes

2024-01-27 17:31 UTC, sonichi commented on website/docs/Examples.md
> +   - Natural Language Text to SQL Query using the [Spider](https://yale-lily.github.io/spider) Text-to-SQL Benchmark - [View Notebook](https://github.com/microsoft/autogen/blob/main/notebook/agentcha
Is this the right place? I think the tool use section is a better fit.

2024-01-27 18:28 UTC, sonichi approved these changes

2024-01-27 19:02 UTC, merged