Add support for Anthropic Claude models
microsoft/autogen pull request #2245
Opened 2024-04-01 22:09 UTC by levscaut

## Why are these changes needed?

AutoGen do not currently have support for the Anthropic API. 

## Related issue number

#2164 

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

2024-04-01 22:13 UTC, levscaut commented
I'm actually not sure about where to put the AnthropicClient class. It will be much more convinient to use Anthropic API if we can treat this client as same level as OpenAIClient in `autogen/oai/client.py`, compared to have it as an extrernal custom client.

2024-04-02 05:30 UTC, ekzhu requested changes
For such important topic, it should be on the website rather than a notebook example.

2024-04-02 05:30 UTC, ekzhu commented on notebook/agentchat_anthropic.ipynb
Suggestions:
1. Remove the section "Set your API Endpoint" and use a raw Python dictionary config_list. This greatly simplifies the setup for the notebook example. 
2. Notebook examples are currently hard to surface through the website. However we can render web page directly from notebooks. Suggest putting this notebook under `/website/docs/topics/non-openai-models/` and under `/website` run `python process_notebooks.py render` to render it as a webpage. See other notebooks in the same directory as example. Rember to also update https://github.com/microsoft/autogen/blob/main/website/docs/topics/non-openai-models/about-using-nonopenai-models.md to add a link to the page.

2024-04-02 05:30 UTC, ekzhu commented on notebook/agentchat_anthropic.ipynb
To build website locally, follow instructions in https://microsoft.github.io/autogen/docs/Contribute#documentation

2024-04-02 05:35 UTC, thinkall commented
> I'm actually not sure about where to put the AnthropicClient class. It will be much more convinient to use Anthropic API if we can treat this client as same level as OpenAIClient in `autogen/oai/client.py`, compared to have it as an extrernal custom client. @thinkall it will be great if I can have your advice!

Thanks for the contribution, @levscaut ! Currently, for the ease of  maintainance, we only have openAI compatible client in the core. For non-OpenAI style client, a tutorial/notebook example would be simpler, but we could add it to the `oai` module if we find it's better.

Could you also add an example here: https://microsoft.github.io/autogen/docs/topics/non-openai-models/about-using-nonopenai-models? Create a page like `Mistral AI`. Thanks.

2024-04-02 06:52 UTC, ekzhu commented
Agree with @thinkall. we can start with a notebook and have people try it out. Once the code is stable and we get resources for testing non-openai APIs, we can formalize it into a first-class client.

2024-04-02 12:49 UTC, olgavrou approved these changes
Agree with the comments for moving in the right place, but other than that LGTM

2024-04-02 16:51 UTC, levscaut commented
Thanks for the advice! I've move the notebook to website and added link to it.

2024-04-02 23:21 UTC, ekzhu requested changes

2024-04-02 23:21 UTC, ekzhu commented on website/docs/topics/non-openai-models/cloud-anthropic.ipynb
This block:

```python
config_list_custom = autogen.config_list_from_json(
    "OAI_CONFIG_LIST",
    filter_dict={"model_client_cls": ["AnthropicClient"]},
)
```

Instead of using `config_list_from_json`, use a raw Python list of a dictionary for the AnthropicClient.

2024-04-02 23:21 UTC, ekzhu commented on website/docs/topics/non-openai-models/cloud-anthropic.ipynb
This is part of the effort to make notebook easier to use. See https://github.com/microsoft/autogen/issues/2139

2024-04-02 23:21 UTC, ekzhu commented on website/docs/topics/non-openai-models/cloud-anthropic.ipynb
This line at the top:

```
NOTE: Depending on what model you use, you may need to play with the default prompts of the Agent's
```

I think it should be "... refine the system messages of the agents"

2024-04-03 02:56 UTC, levscaut commented on website/docs/topics/non-openai-models/cloud-anthropic.ipynb
Thanks for the advice. I had some confusion about the raw config part before but now I've fixed it. I also remove the NOTE line on top.

2024-04-03 22:13 UTC, ekzhu approved these changes

2024-04-03 22:28 UTC, merged