Create JSON_mode_example.ipynb
microsoft/autogen pull request #2554
Opened 2024-04-30 23:04 UTC by Aretai-Leah

## Why are these changes needed?

An example of JSON mode usage in notebook format.

## Related issue number

Closes #2224

## Checks

- [ x ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ x ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ x ] I've made sure all auto checks have passed.

2024-04-30 23:26 UTC, Aretai-Leah commented
@microsoft-github-policy-service agree

2024-05-01 04:12 UTC, ekzhu commented on notebook/JSON_mode_example.ipynb
Some quick comments:
1. I see the warning "No default IOStream has been set, defaulting to IOConsole.". Can you upgrade `pyautogen` version to the latest to get rid of the warnings.
2. use `chat_result = ... initiate_chat(...)` to avoid printing out ugly text in the cell output. 
3. How does the JSON model help with speaker transition, I am trying to find it in the notebook.

2024-05-01 05:04 UTC, Aretai-Leah commented on notebook/JSON_mode_example.ipynb
1 & 2, yep done. will update shortly. 
3.  Its under the friendly and suspicious agents section when the definition is defined. However, I'll  label it and explain it more clearly, should be clearer than it is.

2024-05-01 09:18 UTC, Josephrp requested changes
let's try to expand , and refocus the theme to something that will resonate or be familiar to the audience, for example the easiest would be to reframe the agents for "business" , like they could be a group of lawyers , or a group of board room advisors (with different roles) , something like that. i also like the negotiation part a lot, but you can bring it home with a more applied business theme , and nested decisions for tool use i think it's one of the good things abotu JSON mode. something else : json mode as input to datasets processing. so it's a good start, but some work ahead to make it perfect for the audience, perhaps 🚀

2024-05-02 01:40 UTC, Aretai-Leah commented
ok I've updated the notebook to be clearer about the role of Description, including adding an image. 

I've also reframed the example to cover prompt hack mitigation and included a basic hack as the example.  hopefully infosec /cogsec resonates?

2024-05-02 06:05 UTC, ekzhu commented on notebook/JSON_mode_example.ipynb
To make this notebook rendered on our website, please follow the instruction here: https://microsoft.github.io/autogen/docs/contributor-guide/documentation#how-to-get-a-notebook-rendered-on-the-website

2024-05-02 22:49 UTC, Aretai-Leah commented on notebook/JSON_mode_example.ipynb
ok done, I think that's all correct.

2024-05-03 00:54 UTC, ekzhu commented on notebook/JSON_mode_example.ipynb
Let's add `front_matter` to the top-level metadata field. Right now, it is in a cell's metadata field.

2024-05-03 00:55 UTC, ekzhu commented on notebook/JSON_mode_example.ipynb
Scroll to the bottom of the file to find it.

2024-05-03 01:03 UTC, Aretai-Leah commented on notebook/JSON_mode_example.ipynb
Oh oops. Well, that's fixed.

2024-05-03 05:59 UTC, ekzhu requested changes

2024-05-03 05:59 UTC, ekzhu commented on notebook/JSON_mode_example.ipynb
Let's remove the first cell with the code lab link as it will be automatically generated once rendered as webpage. This should fix the error in CI: 

https://github.com/microsoft/autogen/actions/runs/8932617762/job/24542058199?pr=2554#step:8:58

@jackgerrits do we have any guidelines around where to put images?

2024-05-03 13:19 UTC, jackgerrits commented on notebook/JSON_mode_example.ipynb
Other notebooks just store their assets in the root of the notebook/ directory. Seems fine to do the same

2024-05-06 02:08 UTC, Aretai-Leah reviewed
ah thanks, I used another AG notebook as an example, and it was present. Didn't think to remove it.

2024-05-21 04:27 UTC, Aretai-Leah commented
ok, so I've made the suggested changes, but I can see there are some failing checks. Apologies, but its not clear to me what those errors mean or how I would resolve them.  The notebook executes fine and I removed the cell with the code lab link.

2024-05-21 17:30 UTC, ekzhu commented
Re pre-commit failure: https://microsoft.github.io/autogen/docs/contributor-guide/pre-commit

Re dock check failure: follow this to set up local website: https://microsoft.github.io/autogen/docs/contributor-guide/documentation. And try to debug the .mdx file generated from the notebook (should be in /website/docs/notebooks after running process_notebooks.py)

2024-05-22 07:16 UTC, Aretai-Leah reviewed
fixed formatting errors

2024-05-23 00:57 UTC, Aretai-Leah commented
ok, should be all ready and fixed up.

2024-05-24 13:12 UTC, ekzhu approved these changes

2024-05-24 13:16 UTC, merged