add claude 3.5 sonnet to pricing
microsoft/autogen pull request #2981
Opened 2024-06-20 17:57 UTC by garnermccloud

## Why are these changes needed?

Adds pricing info for the new [Anthropic Claude 3.5 Sonnet model](https://docs.anthropic.com/en/docs/about-claude/models#model-comparison).

## Related issue number

## Checks

- [ ] I've included any doc changes needed for https://microsoft.github.io/autogen/. See https://microsoft.github.io/autogen/docs/Contribute#documentation to build and test documentation locally.
- [ ] I've added tests (if relevant) corresponding to the changes introduced in this PR.
- [ ] I've made sure all auto checks have passed.

2024-06-20 18:18 UTC, Hk669 approved these changes
thanks @garnermccloud, for the changes. looks good to me.

2024-06-20 18:33 UTC, Hk669 commented
also, can you give us some feedback on the Anthropic Client's working status? that'll help us improve it for the community. thanks @garnermccloud

2024-06-20 18:38 UTC, garnermccloud commented
> also, can you give us some feedback on the Anthropic Client's working status? that'll help us improve it for the community. thanks @garnermccloud

Will do. I'll follow up with any issues and fixes if I see them.

2024-06-20 18:44 UTC, Hk669 commented
> Will do. I'll follow up with any issues and fixes if I see them.

also do visit our current roadmap #2946  for the next release and would love to hear any contributions from you. thanks

2024-06-20 19:14 UTC, garnermccloud commented
@Hk669 - I found a bug when using the GroupChat agent:
```
anthropic.BadRequestError: Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'messages.0.name: Extra inputs are not permitted'}}
``` 

I have a fix for it, and it touches the same file. I can either add it to this PR or create a new one. What's your recommendation?  

After that fix, the AnthropicClient worked great. Nice work!

2024-06-20 19:27 UTC, Hk669 commented
> @Hk669 - I found a bug when using the GroupChat agent:
> 
> ```
> anthropic.BadRequestError: Error code: 400 - {'type': 'error', 'error': {'type': 'invalid_request_error', 'message': 'messages.0.name: Extra inputs are not permitted'}}
> ```
> 
> I have a fix for it, and it touches the same file. I can either add it to this PR or create a new one. What's your recommendation?
> 
> After that fix, the AnthropicClient worked great. Nice work!

can you please add it to the same PR.

2024-06-20 20:34 UTC, marklysze commented
Thanks for testing @garnermccloud, would you be able to provide any sample code that you're running so I can test against your error as well? I'm looking at function/tool use testing now.

2024-06-20 20:48 UTC, garnermccloud commented
> Thanks for testing @garnermccloud, would you be able to provide any sample code that you're running so I can test against your error as well? I'm looking at function/tool use testing now.

Here you go @marklysze 
```
import os

from autogen import AssistantAgent, GroupChat, GroupChatManager, UserProxyAgent

anthropic_llm_config = {
    "cache_seed": None,
    "config_list": [
        {
            "model": "claude-3-5-sonnet-20240620",
            "api_key": os.getenv("ANTHROPIC_API_KEY"),
            "api_type": "anthropic",
        }
    ],
}


def main():
    llm_config = anthropic_llm_config
    assistant = AssistantAgent(
        "inner-assistant",
        llm_config=llm_config,
        is_termination_msg=lambda x: x.get("content", "").find("TERMINATE") >= 0,
    )

    code_interpreter = UserProxyAgent(
        "inner-code-interpreter",
        human_input_mode="NEVER",
        code_execution_config={
            "work_dir": "coding",
            "use_docker": True,
        },
        default_auto_reply="",
        is_termination_msg=lambda x: x.get("content", "").find("TERMINATE") >= 0,
    )

    groupchat = GroupChat(
        agents=[assistant, code_interpreter],
        messages=[],
        speaker_selection_method="round_robin",  # With two agents, this is equivalent to a 1:1 conversation.
        allow_repeat_speaker=False,
        max_round=8,
    )

    manager = GroupChatManager(
        groupchat=groupchat,
        is_termination_msg=lambda x: x.get("content", "").find("TERMINATE") >= 0,
        llm_config=llm_config,
    )

    task = "On which days in 2024 was Microsoft Stock higher than $370?"

    user_proxy = UserProxyAgent(
        "user_proxy",
        human_input_mode="NEVER",
        code_execution_config=False,
        default_auto_reply="",
        is_termination_msg=lambda x: True,
    )

    user_proxy.initiate_chat(manager, message=task)


if __name__ == "__main__":
    main()
```

2024-06-20 21:10 UTC, marklysze commented
Thanks @garnermccloud! I'll test with that as well, and I have some code changes to better support tool calls as well which I'll recommend changes to in this PR.

2024-06-20 23:03 UTC, marklysze commented
Okay, please see my suggested code changes. @garnermccloud's works well to remove the `name` on the messages, as well as fix the reference for the client_utils. I've added some code suggestions to handle tool calling better.

I've also tested the code changes with single tool, multi-tool, simple back and forth chat, termination, and a more comprehensive group chat debate (which worked really well with Claude Sonnet 3.5). It worked well for these cases.

2024-06-21 01:25 UTC, marklysze commented
As I'm testing, I can see that the `create` function isn't returning `ChatCompletion` response object. I believe this needs to change so the response can be managed throughout the rest of AutoGen. I'm working through converting it now.

2024-06-21 03:35 UTC, marklysze commented
Hey @garnermccloud, I've updated the code a bit to:
- align tool calls and results with Anthropic's expected formats
- changed the `create` function to return a response in the standard format

Your changes were working well and remain as is.

Are you able to test out the current code?

P.s. Anthropic's API was down for about an hour but seems to be back up now.

2024-06-21 03:49 UTC, qingyun-wu commented
> Hey @garnermccloud, I've updated the code a bit to:
> 
> * align tool calls and results with Anthropic's expected formats
> * change the `create` function to return a response in the standard format
> 
> Your changes were working well and remain as is.
> 
> Are you able to test out the current code? I'll continue to test as well.
> 
> P.s. Anthropic's API was down for about an hour but seems to be back up now.

I've tested the code. It works well!

2024-06-21 04:01 UTC, Hk669 commented on autogen/oai/anthropic.py
>      def get_usage(response: Message) -> Dict:
can you check the dtype of the `response: Message`

2024-06-21 05:04 UTC, marklysze commented
I think it's worth a test with the updated Anthropic client class, just updated. I think specific workflows like "auto" speaker selection in group chat could be better catered for but it is functional.

2024-06-21 05:35 UTC, Hk669 commented on autogen/oai/anthropic.py
> +        anthropic_messages = oai_messages_to_together_messages(params)
```suggestion
        anthropic_messages = oai_messages_to_anthropic_messages(params)
```

2024-06-21 05:35 UTC, Hk669 commented on autogen/oai/anthropic.py
> +def oai_messages_to_together_messages(params: Dict[str, Any]) -> list[dict[str, Any]]:
```suggestion
def oai_messages_to_anthropic_messages(params: Dict[str, Any]) -> list[dict[str, Any]]:
```

2024-06-21 06:25 UTC, Hk669 approved these changes
Looks great! Thanks for the fixes.

2024-06-21 06:44 UTC, qingyun-wu commented
@garnermccloud @Hk669 @marklysze added a group chat example and ran the notebook. Please check! Thanks!

2024-06-21 07:06 UTC, Hk669 approved these changes
looks great! thanks @qingyun-wu

2024-06-21 07:27 UTC, yiranwu0 commented
Why there are so many changes?

I just do 
```python
        for i in range(len(anthropic_params["messages"])):
            if anthropic_params["messages"][i]["role"] != "tool_use" and "name" in anthropic_params["messages"][i]:
                del anthropic_params["messages"][i]["name"]
```
in line 160 after `anthropic_params["messages"] = params["messages"]` and it works.

2024-06-21 07:28 UTC, yiranwu0 requested changes
Why there are so many changes?

I just do 
```python
        for i in range(len(anthropic_params["messages"])):
            if anthropic_params["messages"][i]["role"] != "tool_use" and "name" in anthropic_params["messages"][i]:
                del anthropic_params["messages"][i]["name"]
```
in line 160 after `anthropic_params["messages"] = params["messages"]` and it works.

2024-06-21 07:40 UTC, yiranwu0 commented
I suggest first create a new PR to get the two issues mentioned fixed first, at least to get the client working in groupchat.
We can keep this PR to fix other issues. 
These errors bypassing meaning the test is not properly created, we also need to add that.

2024-06-21 12:27 UTC, qingyun-wu approved these changes
Looks good!

2024-06-21 12:27 UTC, qingyun-wu commented
> Why there are so many changes?
> 
> I just do
> 
> ```python
>         for i in range(len(anthropic_params["messages"])):
>             if anthropic_params["messages"][i]["role"] != "tool_use" and "name" in anthropic_params["messages"][i]:
>                 del anthropic_params["messages"][i]["name"]
> ```
> 
> in line 160 after `anthropic_params["messages"] = params["messages"]` and it works.

@yiranwu0, this suggested change does not work in the case of groupchat with tool calling (test the groupchat example added in the notebook).

2024-06-21 14:42 UTC, yiranwu0 commented
> @yiranwu0, this suggested change does not work in the case of groupchat with tool calling (test the groupchat example added in the notebook).

Got it! Didn't go through the changes in notebook...

2024-06-21 16:46 UTC, merged